name: Build and deploy Node.js app to Azure Web App - livestreamer-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build
        run: |
          npm install
          npx prisma generate
          npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Copy static files to standalone
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Upload artifact to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name storefiletransform \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --overwrite true \
              --source .next/standalone \
              --destination livestream
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Create destination directory
        run: mkdir -p downloaded-artifacts

      - name: Download artifact from Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob download-batch \
              --account-name storefiletransform \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --source livestream \
              --destination ${{ github.workspace }}/downloaded-artifacts
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3075823679CF4BB8820A203445876498 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5A8E0C12B1534348B4E1EF9EF41192B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDCE82746C4B43D4A7E29CA80F5D2CB2 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "livestreamer-app"
          slot-name: "Production"
          package: ./downloaded-artifacts
